import Paper from "app/components/paper";

export default function Research(){

    const paper_list = [
        {
            title: "Contact cosmetic surgery on legendrian knots in integer homology sphere L-spaces",
            authors: "Apratim Chakraborty and Tanushree Shah",
            year: "2026",
            link: "https://arxiv.org/pdf/2606.27485",
            abstract: "We extend the study of contact cosmetic surgeries to Legendrian knots in integer homology sphere L-spaces. We prove that the contact cosmetic surgery conjecture holds for all non-trivial Legendrian knots in this setting, with the possible exception of Lagrangian slice knots. Our argument adapts and refines techniques from the $S^3$ case to the broader context of L-spaces, incorporating constraints arising from Heegaard Floer theory",
            note: ""
        },
        {
            title: "A spanning tree model for chromatic homology",
            authors: "Aninda Banerjee, Apratim Chakraborty and Pravakar Paul",
            year: "2025",
            link: "https://arxiv.org/abs/2504.00834",
            abstract: "After the discovery of Khovanov homology, which categorifies the Jones polynomial, an analogous categorification of the chromatic polynomial, known as chromatic homology, was introduced. Its graded Euler characteristic recovers the chromatic polynomial. In this paper, we present a spanning tree model for the chromatic complex, i.e., we describe a chain complex generated by certain spanning trees of the graph that is chain homotopy equivalent to the chromatic complex. We employ the spanning tree model over $\\mathcal{A}_m:=\\mathbb{Z}[x]\\langle x_m \\rangle$ algebra to answer two open questions. First, we establish the conjecture posed by Sazdanovic and Scofield regarding the homological span of chromatic homology over $\\mathcal{A}_m$ algebra, demonstrating that for any graph G with v vertices and b blocks, the homological span is v−b. Additionally, we prove a conjecture of Helme-Guizon, Przytycki, and Rong concerning the existence of torsion of order dividing m in chromatic homology over $\\mathcal{A}_m$ algebra.",
            note: ""  
        },
        {
            title: "A spanning tree model for Khovanov homology, Rasmussen's $s$-invariant and exotic discs in the 4-ball",
            authors: "Aninda Banerjee and Apratim Chakraborty",
            year: "2025",
            link: "https://arxiv.org/abs/2504.02625",
            abstract: "The checkerboard coloring of knot diagrams offers a graph-theoretical approach to address topological questions. Champanerkar and Kofman defined a complex generated by the spanning trees of a graph obtained from the checkerboard coloring whose homology is the reduced Khovanov homology. Notably, the differential in their chain complex was not explicitly defined. We explicitly define the combinatorial form of the differential within the spanning tree complex. We additionally provide a description of Rasmussen's $s$-invariant within the context of the spanning tree complex. Applying our techniques, we identify a new infinite family of knots where each of them bounds a set of exotic discs within the 4-ball.",
            note: "This is still a work in progress as the current version contains a crucial mistake in the example of exotic disks (pointed out by Kyle Hayden), and we are also working on improving the description of the differential."
        }

]

    return(
        <section>
            <p className="mb-6">
            I am interested in low-dimensional objects like knots/links, 3-manifolds, 4-manifolds and graphs. Moreover, I like to study these objects using invariants such as Khovanov homology, Heegard Floer homology, knot Floer homology, and Chromatic homology. Currently, I am interested in the following topics: 
            <ol className="m-3 list-disc">
                <li>Spanning tree models of these homology theories and their applications</li>
                <li>Problems related to Dehn surgery</li>
            </ol>
            </p>  
            <h1 className="mb-6 text-xl font-semibold tracking-tighter">Preprints</h1>
            <div className="mb-8 mx-2">
                <ol className="list-decimal">
                  {paper_list.map((paper,id) => <li className="mb-4" key={id}>
                    <Paper 
                    title={paper.title}
                    authors={paper.authors}
                    abstract={paper.abstract}
                    year={paper.year}
                    link={paper.link}
                    note={paper.note}/>
                  </li>)}
                </ol>
            </div>
        </section>
    )
}